[package]
name = "smt_io_adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
thiserror = "1.0"
libc = "0.2"
core_affinity = "0.8"