[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
thiserror = "1.0"
libc = "0.2"
core_affinity = "0.8"  # Corrected name with underscore